# train_test_split:

*** This concept covers the train_test_split technique : ***
** Data Splitting Congifuration **
       1.random_state
       2.stratify

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score
import statsmodels.api as sm

In [2]:
eng = ['engineer'] * 8000
doc = ['docter'] * 2000
eng.extend(doc)

In [3]:
len(eng)

10000

In [5]:
df = pd.read_csv(r"D:\Machine Learning\Data-Splitting-and-Model-Validation\Sources\dataset.csv")

In [6]:
df['profession'] = eng
df.head()

   age  experience_years  education_level  hours_per_week  salary profession
0   56                14                2              37  164160   engineer
1   46                 7                1              50  106211   engineer
2   32                 9                1              41   36124   engineer
3   60                 4                1              33   23819   engineer
4   25                18                2              37  115822   engineer

In [7]:
# predict the salary
# predict the profession

In [36]:
# predict the salary
# y = salary
# x = hours_per_week, experience_years, age
df.columns

Index(['age', 'experience_years', 'education_level', 'hours_per_week',
       'salary', 'profession'],
      dtype='str')

# Training Phase - 1 : # for salary prediction (Function - train_test_split)

In [ ]:
# train_test_split :

In [56]:
X = df[['age', 'experience_years', 'education_level', 'hours_per_week']]
Y = df[['salary']]

In [66]:
x_train, x_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size = 0.2,
    random_state = 42
)

In [67]:
x_train.head()

      age  experience_years  education_level  hours_per_week
9254   42                 3                2              65
1561   28                 9                2              57
1670   27                39                2              59
6087   41                29                1              32
6669   54                24                1              44

In [68]:
len(y_train)

8000

In [69]:
len(x_train)

8000

In [70]:
len(y_test)

2000

In [71]:
len(x_test)

2000

In [72]:
model = sm.OLS(y_train, x_train)
results = model.fit()

In [73]:
# 0.790 - without random state results 
# 0.792 - without random state results 
# 0.788 - without random state results 

# after fixing the random state, the result is 0.789
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                 salary   R-squared (uncentered):                   0.789
Model:                            OLS   Adj. R-squared (uncentered):              0.789
Method:                 Least Squares   F-statistic:                              7494.
Date:                Sat, 25 Jul 2026   Prob (F-statistic):                        0.00
Time:                        19:24:51   Log-Likelihood:                         -98803.
No. Observations:                8000   AIC:                                  1.976e+05
Df Residuals:                    7996   BIC:                                  1.976e+05
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
age                819.7491     38.244     21.435      0.000     744.781     894.717
experience_years   600.0289     51.980     11.543      0.000     498.134     701.924
education_level   1.151e+04    682.952     16.852      0.000    1.02e+04    1.28e+04
hours_per_week     856.2049     35.303     24.253      0.000     787.002     925.408
==============================================================================
Omnibus:                     1261.852   Durbin-Watson:                   1.992
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              288.238
Skew:                          -0.022   Prob(JB):                     2.57e-63
Kurtosis:                       2.071   Cond. No.                         71.1
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Training Phase - 2 : # for profession prediction (Function - train_test_split)

In [12]:
X_cat = df[['age', 'experience_years', 'education_level', 'hours_per_week']]
Y_cat = df[['profession']]

In [13]:
X_cat.count()

age                 10000
experience_years    10000
education_level     10000
hours_per_week      10000
dtype: int64

In [14]:
Y_cat.count()

profession    10000
dtype: int64

In [15]:
x_train_cat, x_test_cat, y_train_cat, y_test_cat = train_test_split(
    X_cat,
    Y_cat,
    test_size = 0.2,
    random_state = 42,
    stratify = Y_cat
)

In [16]:
x_train_cat.count()

age                 8000
experience_years    8000
education_level     8000
hours_per_week      8000
dtype: int64

In [17]:
x_test_cat.count()

age                 2000
experience_years    2000
education_level     2000
hours_per_week      2000
dtype: int64

In [18]:
y_train_cat.count()

profession    8000
dtype: int64

In [19]:
y_test_cat.count()

profession    2000
dtype: int64

In [20]:
# y_train_cat.groupby(y_train_cat).count()

In [21]:
y_train_cat.iloc[:, 0].value_counts() # with stratify

profession
engineer    6400
docter      1600
Name: count, dtype: int64

In [22]:
y_test_cat.iloc[:, 0].value_counts() # with stratify

profession
engineer    1600
docter       400
Name: count, dtype: int64

# cross_validation_score :

In [25]:
# this is same as the k fold validation but it were automatically fetch the data's from trained data..


model = sm.OLS()
score = cross_val_score(
    model,
    X,
    Y,
    scoring = ['r2'],
    cv = 5 # same spliting
)

TypeError: OLS.__init__() missing 1 required positional argument: 'endog'